# =============================================================================
# Population-Specific Structural Variant Analysis — S. eubayanus
# =============================================================================
# Description:
#   Identifies structural variants (SVs) that are unique to a single population
#   group among S. eubayanus strains. SVs detected by MUM&Co (vs. CBS12357
#   reference) are loaded from TSV files, mapped to population groups, and
#   filtered to retain only those found exclusively in one group.
#   Results include:
#     - Count of population-specific SVs per group
#     - Genomic position histograms of unique SVs by type and population
#     - Filtering by SV size (< 10 kb) to focus on small/medium SVs
#   A secondary analysis identifies population-specific SVs from a different
#   set of TSV files (CBS_* prefix naming convention, from MUM&Co v3.8).
#
# Input:
#   - *.SVs_all.tsv files in the working directory (one per strain comparison)
#     Generated by MUM&Co; key columns: ref_chr, ref_start, ref_stop, SV_type, size
#
# Output:
#   - Summary table: unique SV counts per population and type (printed)
#   - Histograms of unique SV genomic positions (displayed interactively)
#
# Dependencies:
#   install.packages(c("tidyverse", "readr", "dplyr", "ggplot2"))
#
# Note:
#   Set your working directory to the folder containing the .SVs_all.tsv files
#   before running this script (setwd("path/to/tsv/files"))
# =============================================================================

# =============================================================================
# PART 1: Unique SV analysis using raw strain naming (without CBS_ prefix)
# =============================================================================

library(tidyverse)

# Step 1: List all MUM&Co TSV output files in the working directory
tsv_files <- list.files("./", pattern = "\\.tsv$", full.names = TRUE)

# Step 2: Read all TSV files, combine into a single data frame,
#         adding a 'strain' column derived from each filename
df_all <- map_dfr(tsv_files, ~ read_tsv(.x, col_types = cols()) %>% 
                    mutate(strain = tools::file_path_sans_ext(basename(.x))))

# Step 3: Define strain-to-population mapping
# Populations: Holartic (admixed), PA (Patagonia), PB1-PB5 (Patagonian subpopulations)
strain2group <- tribble(
  ~strain,      ~group,
  "UCD646",     "Holartic",
  "UCD650",     "Holartic",
  "yHRVM108",   "Holartic",
  "CDFM21L.1",  "Holartic",
  "AA3",        "PA",
  "AA4",        "PA",
  "CL450.1",    "PB1",
  "CL1005.1",   "PB1",
  "CL815.1",    "PB1",
  "CL467.1",    "PB1",
  "CL715.1",    "PB2",
  "CL1111.1",   "PB2",
  "CL248.1",    "PB2",
  "CL1101.1",   "PB2",
  "CL607.1",    "PB3",
  "CL905.1",    "PB3",
  "S13-HH",     "PB3",
  "CL216.1",    "PB3",
  "E12",        "PB4",
  "NR2",        "PB4",
  "CO150",      "PB5"
)

# Step 4: Join population group to each SV entry
df_all <- df_all %>% 
  left_join(strain2group, by = "strain")

# Step 5: Create a unique SV identifier (chromosome + start + stop + SV type)
df_all <- df_all %>% 
  mutate(
    sv_id = paste(ref_chr, ref_start, ref_stop, SV_type, sep = "_")
  )

# Step 6: Count how many population groups each SV appears in
sv_group_counts <- df_all %>% 
  distinct(sv_id, group) %>%   # cada combinación sv–grupo solo una vez
  count(sv_id, name = "n_groups")

# Step 7: Retain only SVs found in exactly one population group (population-specific)
sv_unique <- sv_group_counts %>% 
  filter(n_groups == 1) %>% 
  pull(sv_id)

# Step 8: Extract population-specific SVs with their chromosomal coordinates
df_unique <- df_all %>% 
  filter(sv_id %in% sv_unique) %>% 
  distinct(sv_id, group, ref_chr, ref_start, ref_stop, SV_type)

# Step 9: Count population-specific SVs per group (sorted descending)
df_unique %>% 
  count(group) %>% 
  arrange(desc(n))

# Step 10: Histogram of genomic positions of population-specific SVs by group
df_unique %>% 
  mutate(midpoint = (ref_start + ref_stop) / 2) %>% 
  ggplot(aes(x = midpoint, fill = group)) +
  geom_histogram(bins = 50, position = "dodge", colour = "black") +
  facet_wrap(~ group, scales = "free_x", ncol = 2) +
  labs(
    x     = "Posición en el cromosoma (bp)",
    y     = "Número de SVs únicas",
    fill  = "Grupo",
    title = "Distribución de SVs específicas por grupo"
  ) +
  theme_minimal()

# =============================================================================
# PART 2: Unique SV analysis using CBS_* naming convention (MUM&Co v3.8 output)
# =============================================================================

# Verify current working directory and list available TSV files
getwd()

# Listar todos los .tsv en ese directorio (sin especificar subcarpetas)
list.files(pattern = "\\.tsv$")

tsv_files <- list.files(pattern = "\\.tsv$", full.names = TRUE)
print(tsv_files)

library(readr)
library(dplyr)

df_all <- purrr::map_dfr(tsv_files, function(f) {
  read_tsv(f, col_types = cols()) %>%
    mutate(
      strain = basename(f) %>%
        tools::file_path_sans_ext() %>%
        # quita la parte ".SVs_all" si ese es el sufijo
        sub("\\.SVs_all$", "", .)
    )
})

# Comprueba que cargó algo:
glimpse(df_all)
unique(df_all$strain)


# Define strain-to-population mapping (CBS_* file naming from MUM&Co v3.8)

strain2group <- tribble(
  ~strain,        ~group,
  "CBS_UCD646",   "Holartic",
  "CBS_UCD650",   "Holartic",
  "CBS_yHRVM108", "Holartic",
  "CBS_AA3",      "PA",
  "CBS_AA4",      "PA",
  "CBS_CL450",    "PB1",
  "CBS_CL1005",   "PB1",
  "CBS_CL815",    "PB1",
  "CBS_CL467",    "PB1",
  "CBS_CL715",    "PB2",
  "CBS_CL1111",   "PB2",
  "CBS_CL248",    "PB2",
  "CBS_CL1101",   "PB2",
  "CBS_CL607",    "PB3",
  "CBS_CL905",    "PB3",
  "CBS_S13HH",    "PB3",
  "CBS_CL216",    "PB3",
  "CBS_E12",      "PB4",
  "CBS_NR2",      "PB4",
  "CBS_CO150",    "PB5"
)

# Join population group to the variant table
df_all <- df_all %>%
  left_join(strain2group, by = "strain")

# Create a unique SV identifier (chromosome + start + stop + SV type)
df_all <- df_all %>%
  mutate(
    sv_id = paste(ref_chr, ref_start, ref_stop, SV_type, sep = "_")
  )

# Inspect SV lengths (sorted by largest first) — for exploratory purposes
mutate(df_all, length= ref_stop - ref_start) %>% arrange(-length) -> carlos_df

# Count how many population groups each SV appears in
sv_group_counts <- df_all %>%
  distinct(sv_id, group) %>%   # ensure each sv_id–group pair is counted once
  count(sv_id, name = "n_groups")

# Retain only SVs found in exactly one population group (population-specific)
unique_sv_ids <- sv_group_counts %>%
  filter(n_groups == 1) %>%
  pull(sv_id)


df_unique <- df_all %>% 
  filter(sv_id %in% unique_sv_ids, !is.na(group)) %>% 
  distinct(sv_id, group, ref_chr, ref_start, ref_stop, SV_type)



df_unique <- df_all %>%
  filter(
    sv_id %in% unique_sv_ids,
    !is.na(group),
    size < 10000
  ) %>%
  distinct(sv_id, group, ref_chr, ref_start, ref_stop, SV_type, size)

# Count population-specific SVs by group and SV type
df_counts <- df_unique %>%
  count(group, SV_type, name = "n") %>%
  arrange(group, desc(n))

print(df_counts)

# Recode SV_type into broader SV categories for cleaner visualization
# (deletion_mobile + deletion_novel → "deletion"; insertion_mobile + insertion_novel → "insertion")
df_unique <- df_unique %>%
  mutate(
    SV_group = case_when(
      SV_type %in% c("deletion_mobile", "deletion_novel")   ~ "deletion",
      SV_type %in% c("insertion_mobile", "insertion_novel") ~ "insertion",
      TRUE                                                   ~ SV_type
    )
  )

# Count population-specific SVs by group and SV category
df_counts_grouped <- df_unique %>%
  count(group, SV_group, name = "n") %>%
  arrange(group, desc(n))

print(df_counts_grouped)
view(df_counts_grouped)

# Plot genomic position distribution of population-specific SVs, faceted by group

library(ggplot2)
view(df_unique)

df_unique %>%
  mutate(midpoint = (ref_start + ref_stop) / 2) %>%
  ggplot(aes(x = midpoint, fill = SV_group)) +
  geom_histogram(
    bins     = 50,
    position = "stack",
    colour   = "black",
    alpha    = 0.8
  ) +
  facet_wrap(~ group, scales = "free_x", ncol = 2) +
  scale_fill_brewer(palette = "Set2") +
  labs(
    x     = "Posición en el cromosoma (bp)",
    y     = "Número de SVs únicas",
    fill  = "Tipo de SV (agrupado)",
    title = "Distribución de SVs específicas por grupo y tipo"
  ) +
  theme_minimal() +
  theme(
    strip.text       = element_text(face = "bold"),
    panel.grid.minor = element_blank()
  )

# =============================================================================
# SECTION: Holarctic-admixed strains — population-specific SV deep dive
# =============================================================================

# Filter to retain only Holarctic-admixed population SVs
df_holartic <- df_unique %>%
  filter(group == "Holartic")

# Count unique SVs by type in the Holarctic group
df_holartic %>%
  count(SV_group) %>%
  arrange(desc(n))

# Histogram of Holarctic-specific SV positions on the genome
library(ggplot2)

df_holartic %>%
  mutate(midpoint = (ref_start + ref_stop) / 2) %>%
  ggplot(aes(x = midpoint, fill = SV_group)) +
  geom_histogram(bins = 100, colour = "black", alpha = 0.8) +
  scale_fill_brewer(palette = "Set2") +
  labs(
    x     = "Posición (bp)",
    y     = "Número de SVs únicas",
    fill  = "Tipo SV (agrupado)",
    title = "SVs únicas en el grupo Holartic"
  ) +
  theme_bw()
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# =============================================================================
# SECTION: Chromosomal ideogram visualization with RIdeogram
# =============================================================================
# Install RIdeogram from GitHub if not already installed
install.packages("devtools")
library(devtools)
install_github("zwdzwd/RIdeogram")
library(RIdeogram)

# --- Build karyotype from CBS12357 reference FASTA ---
library(Biostrings)
library(dplyr)
library(tibble)

# Step 1: Read reference genome FASTA (CBS12357 — reference strain)
fasta_file <- "CBS12357_polished_20170509.fa"
genome     <- readDNAStringSet(fasta_file)

# Step 2: Extract chromosome names and lengths from FASTA headers
chr_names   <- names(genome) %>% sub("_polished$", "", .)
chr_lengths <- width(genome)

# Step 3: Build karyotype data frame (chromosome, start=0, end=length)
karyotype <- tibble(
  Chr   = chr_names,
  Start = 0L,
  End   = chr_lengths
)

# Step 4: Add centromere coordinates (CE_start, CE_end)
#         Fill in centromere positions from LRSDAY centromere annotation output


karyotype <- karyotype %>%
  left_join(centromeres, by = "Chr")
karyotype <- karyotype %>%
  filter(Chr != "CBS12357_mtDNA")

# Step 5: Inspect the final karyotype table
print(karyotype)


# Simplify karyotype to only Chr, Start, End (required by ideogram())
karyotype_simple <- karyotype %>%
  select(Chr, Start, End)

# Asegúrate de eliminar la mtDNA si aún no lo hiciste:
karyotype_simple <- karyotype_simple %>%
  filter(Chr != "CBS12357_mtDNA")

# Comprueba:
print(karyotype_simple)

gene_density <- GFFex(input = "CBS12357.final.gff3.gz", karyotype = "karyotype_simple", feature = "gene", window = 1000000)


ideogram(karyotype = karyotype_simple)
convertSVG("chromosome.svg", device = "png")


write.table(
  karyotype_simple,
  file      = "karyotype_simple.txt",
  sep       = "\t",
  row.names = FALSE,   # quita la columna de índices
  col.names = TRUE,    # incluye los nombres de las columnas
  quote     = FALSE    # no encierra en comillas
)


# 2. Llama a GFFex indicando la ruta del karyotype
gene_density <- GFFex(
  input     = "CBS12357.final.gff3.gz",
  karyotype = "karyotype_simple.txt",
  feature   = "gene",
  window    = 10000
)

# 3. Comprueba tu gene_density
head(gene_density)

#Plot combinado de densidades de SVs y genes
ideogram(karyotype = karyotype_simple, overlaid = gene_density)
convertSVG("chromosome.svg", device = "png")

svg2pdf("chromosome.svg", file = "chromosomes", width = 8.2677, height = 11.6929,
        dpi = 300)

# --- Overlay Holarctic-specific SVs on the ideogram ---
library(dplyr)

# Assign colors to each SV category for ideogram markers
colors <- brewer.pal(6, "Set1") 

df_plot <- df_holartic %>%
  dplyr::mutate(
    Type = SV_group,           # Asignar Type según SV_group
    Chr = ref_chr,             # Asignar Chr a ref_chr
    Start = ref_start,         # Asignar Start a ref_start
    End = ref_stop,            # Asignar End a ref_stop
    color = colors[SV_group],  # Asignar color desde la paleta
    Shape = "circle"           # Asignar "circle" a la columna Shape
  ) %>%
  dplyr::select(Type, Shape, Chr, Start, End, color) # Incluir Shape en el select

# Mostrar el DataFrame
print(df_plot)
write.table(df_plot, file = "df_plot.txt", sep = "\t", row.names = FALSE, quote = FALSE)


df_plot2 <- read.table("df_plot.txt", sep = "\t", header = T, stringsAsFactors = F)


#Plot combinado de densidades de SVs y genes
ideogram(karyotype = karyotype_simple, overlaid = gene_density, label = df_plot2, label_type = "marker")

convertSVG("chromosome.svg", device = "pdf")

svg2pdf("chromosome.svg", file = "SVs", width = 8.2677, height = 11.6929,
        dpi = 300)

svg2pdf("chromosome.svg", file = "chromosomes.pdf", width = 8.2677, height = 11.6929, dpi = 300)

#####
# Asegúrate de tener colores asignados correctamente
colors <- c("deletion" = "6a3d9a", 
            "contraction" = "33a02c", 
            "insertion" = "ff7f00", 
            "duplication" = "1f77b4", 
            "inversion" = "d62728",
            "transloc" = "ff1493")

# Asegúrate de que df_plot2 tenga la columna 'color' correctamente asignada
df_plot2 <- df_holartic %>%
  dplyr::mutate(
    Type = SV_group,           # Asignar Type según SV_group
    Chr = ref_chr,             # Asignar Chr a ref_chr
    Start = ref_start,         # Asignar Start a ref_start
    End = ref_stop,            # Asignar End a ref_stop
    color = colors[SV_group],  # Asignar color según SV_group
    Shape = "circle"           # Asignar "circle" a la columna Shape
  ) %>%
  dplyr::select(Type, Shape, Chr, Start, End, color)  # Incluir Shape en el select

# Verificar que df_plot2 tiene los colores asignados correctamente
head(df_plot2)


# Usar ideogram sin pasar col directamente
ideogram(karyotype = karyotype_simple, 
         overlaid = gene_density, 
         label = df_plot2, 
         label_type = "marker")
svg2pdf("chromosome.svg", file = "chromosomes.pdf", width = 8.2677, height = 11.6929, dpi = 300)


# =============================================================================
# SECTION: Overlap of population-specific SVs with annotated genes
# =============================================================================
# Uses GenomicRanges to find genes overlapping SV coordinates.
# Also includes a ±5 kb flanking region analysis.

# Step 1: Install and load Bioconductor packages for genomic range operations
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install(c("GenomicRanges", "rtracklayer", "IRanges"))

library(GenomicRanges)
library(rtracklayer)
library(dplyr)

# Step 2: Import CBS12357 gene annotation (GFF3 format)
gff <- import(gff_file)

# Keep only 'gene' features from the GFF3 annotation
genes <- gff[gff$type == "gene"]


df_plot %>% dplyr::select(Chr, Start, End) %>% mutate(df_svs, end_1= Start + 5000, start_2 = End -5000)  -> df_svs

# Convertir a GRanges
svs_gr_2 <- GRanges(
  seqnames = df_svs$Chr,
  ranges = IRanges(start = df_svs$Start, end = df_svs$end_1)
)

# Convertir a GRanges
svs_gr_3 <- GRanges(
  seqnames = df_svs$Chr,
  ranges = IRanges(start = df_svs$start_2, end = df_svs$End))


# Convertir a GRanges
svs_gr <- GRanges(
  seqnames = df_svs$Chr,
  ranges = IRanges(start = df_svs$Start, end = df_svs$End)
)

mutate(df_svs, length= End - Start) %>% arrange(-length)


# 4. Encontrar superposiciones con genes
overlaps <- findOverlaps(svs_gr, genes)
genes_affected <- genes[subjectHits(overlaps)]
df_genes_affected <- as.data.frame(genes_affected)

# 4. Encontrar superposiciones con genes
overlaps_2 <- findOverlaps(svs_gr_2, genes)
genes_affected_2 <- genes[subjectHits(overlaps_2)]
df_genes_affected_2 <- as.data.frame(genes_affected_2)

# 4. Encontrar superposiciones con genes
overlaps_3 <- findOverlaps(svs_gr_3, genes)
genes_affected_3 <- genes[subjectHits(overlaps_3)]
df_genes_affected_3 <- as.data.frame(genes_affected_3)

rbind(df_genes_affected_2, df_genes_affected_3) %>% as_tibble() %>% distinct(Name, .keep_all = T) -> carlos2_df



## Using pairs to find intersection of overlapping ranges
hits <- findOverlaps(svs_gr, genes)
p <- Pairs(svs_gr, genes, hits=hits)
pintersect(p)



#Ver una tabla resumida con genes únicos afectados:
genes_afectados_unicos <- df_genes_affected %>%
  dplyr::select(seqnames, start, end, strand, ID, Name) %>%
  dplyr::distinct()

#Ver cuántos SVs caen en genes:
length(unique(df_genes_affected$ID))

#Guardar los genes afectados en un archivo .csv
write.csv(genes_afectados_unicos, "genes_afectados_por_SVs.csv", row.names = FALSE)

# Índices de SVs que NO se solapan con ningún gen
non_overlapping_idx <- setdiff(seq_along(svs_gr), queryHits(overlaps))

# Obtener las SVs que no caen dentro de genes
svs_no_genes <- svs_gr[non_overlapping_idx]

# Convertir a data frame
df_svs_no_genes <- as.data.frame(svs_no_genes)
length(unique(df_genes_affected$ID))

BiocManager::install("org.Sc.sgd.db")
library(org.Sc.sgd.db)

# Extraer solo los nombres "YAL062W" (columna Name)
genes_affected_sgd <- genes_afectados_unicos $Name
genes_affected_sgd <- genes_affected_sgd[grepl("^Y[A-Z]{2}[0-9]{3}[CW]$", genes_affected_sgd)]

columns(org.Sc.sgd.db)

# Obtener GO terms
go_terms <- AnnotationDbi::select(
  org.Sc.sgd.db,
  keys = genes_affected_sgd,
  columns = c("GENENAME", "GO", "ONTOLOGY", "DESCRIPTION"),
  keytype = "ORF"
)

# Guardar tabla completa como .csv
write.csv(go_terms, "genes_GO_annotation.csv", row.names = FALSE)

# Contar los términos GO por categoría
top_go <- go_terms %>%
  filter(!is.na(GO)) %>%
  group_by(ONTOLOGY, GO) %>%
  summarise(n = n(), .groups = "drop") %>%
  arrange(ONTOLOGY, desc(n)) %>%
  group_by(ONTOLOGY) %>%
  slice_head(n = 10)

# Gráfico de barras
ggplot(top_go, aes(x = n, y = reorder(GO, n))) +
  geom_bar(stat = "identity", aes(fill = ONTOLOGY)) +
  facet_wrap(~ONTOLOGY, scales = "free_y") +
  labs(title = "Top 10 GO terms by Ontology",
       x = "Count", y = "GO Term") +
  theme_minimal() +
  theme(strip.text = element_text(face = "bold"))


BiocManager::install("clusterProfiler")
BiocManager::install("enrichplot")
BiocManager::install("DOSE") 


library(clusterProfiler)
library(org.Sc.sgd.db)

# genes_affected_sgd debe contener IDs tipo "YAL062W", etc.
ego <- enrichGO(
  gene         = genes_affected_sgd,
  OrgDb        = org.Sc.sgd.db,
  keyType      = "ORF",       # Usa ORF para IDs tipo YXXX
  ont          = "ALL",       # o "BP", "MF", "CC"
  pAdjustMethod = "BH",
  qvalueCutoff  = 0.05,
  readable      = TRUE
)

# Ver resultados
head(ego)

# Graficar los términos GO más enriquecidos
library(enrichplot)
barplot(ego, split = "ONTOLOGY") + facet_wrap(~ONTOLOGY, scales = "free")




